### ISSUE TITLE
Error finding entry types with newer versions of UnityEngine.dll

### ISSUE THREAD

**Issue by maz-net-au** [Eusth/IPA#5]
Newer versions of UnityEngine.dll contain only references to external assemblies. The entry points UnityEngine.Input and UnityEngine.Display are both in 
```
.assembly extern UnityEngine.CoreModule
{
  .ver 0:0:0:0
}
```
If `FindEntryTypes()` in IPA.Patcher returns no results for UnityEngine.dll, setting `engineFile` to UnityEngine.CoreModule.dll works.

**Comment by maz-net-au** [comment]
I forgot to mention, I ran into this error on Mindshow, a free game on steam.

**Comment by jpitty03** [comment]
Was this issue fixed with your edits?

**Comment by maz-net-au** [comment]
Yeah. It worked for me with Mindshow and some other VR games that I was trying to modify.
If you have any issues with it not working, let me know and I'll try fix them for you.

**Comment by jpitty03** [comment]
> Yeah. It worked for me with Mindshow and some other VR games that I was trying to modify.
> If you have any issues with it not working, let me know and I'll try fix them for you.

Works great now. Deleted the IPA.Tests project before building. It was throwing a bunch of errors anyways.

**Comment by kaznikit** [comment]
> Yeah. It worked for me with Mindshow and some other VR games that I was trying to modify.
> If you have any issues with it not working, let me know and I'll try fix them for you.

Could you create new release version with fixed issues?

**Comment by Eusth** [comment]
Thanks for reporting & the fix. I merged the PR and created [a new release](https://github.com/Eusth/IPA/releases/tag/3.4.1).

**Comment by kaznikit** [comment]
Still have the same problem. 
Patching UnityEngine.dll... ERROR: Oops! This should not have happened.
System.Exception: Could not find any entry type!
   в IPA.Patcher.PatchedModule.Patch()
   в IPA.Program.Install(PatchContext context)

**Comment by JillCrungus** [comment]
Confirming that this issue is still present, a temporary workaround is to move or rename the game's UnityEngine.dll, patch it, and then move or rename the DLL back.
